- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Bagel
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  - Packed
  - WonderBox
  - Scoupidia
  - Triumph
  - WhiteBox
  #- Train <- return after station anchoring PR is finished and merged
