#Cult outfit startingGear definitions.
- type: startingGear
  id: CultLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackFilled
    head: ClothingHeadHelmetCult
    neck: BedsheetCult
    outerClothing: ClothingOuterArmorCult
    shoes: ClothingShoesCult
    id: PassengerPDA
    ears: ClothingHeadsetService
    underwearb: ClothingUnderwearBottomBoxersWhite # White-Underwear
  underweart: ClothingUnderwearTopBraWhite # White-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # White-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: CultistGear
