- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - CentralCommandOfficial
  - Captain
  - HeadOfPersonnel
  - HeadOfSecurity
  - ChiefEngineer
  - ChiefMedicalOfficer
  - ResearchDirector
  - Quartermaster
  - Inspector
  primary: false
  weight: 100

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - Warden
  - SeniorOfficer
  - SecurityOfficer
  - Detective
  - SecurityCadet

- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - Quartermaster
  - CargoTechnician
  - SalvageSpecialist

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - HeadOfPersonnel
  - Borg
  - Bartender
  - Janitor
  - Botanist
  - Chaplain
  - Chef
  - Clown
  - Mime
  - Boxer
  - ServiceWorker
  - Librarian
  - Musician
  - Reporter
  - Visitor
  - Zookeeper
  - Passenger

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - ChiefEngineer
  - SeniorEngineer
  - AtmosphericTechnician
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - ChiefMedicalOfficer
  - SeniorPhysician
  - MedicalDoctor
  - Paramedic
  - Chemist
  - MedicalIntern
  - Psychologist

- type: department
  id: Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher
  - Scientist
  - ResearchAssistant

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  primary: false

- type: department
  id: Justice
  description: department-Justice-description
  color: "#710d00"
  roles:
  - Inspector
  - Lawyer
