using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Miracle.Changeling.UI.ListViewSelector;

[GenerateTypedNameReferences]
public sealed partial class ListViewChangelingSelectorWindow : DefaultWindow
{
    public Action<string>? ItemSelected;

    public ListViewChangelingSelectorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void PopulateList(Dictionary<string, string> items)
    {
        ItemsContainer.RemoveAllChildren();

        foreach (var item in items)
        {
            var button = new Button();

            button.Text = item.Value;

            button.OnPressed += _ => ItemSelected?.Invoke(item.Key);

            ItemsContainer.AddChild(button);
        }
    }
}
