using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Borer;

[GenerateTypedNameReferences]
public sealed partial class ScannerWindow : DefaultWindow
{
    public ScannerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

